# Generated by Django 4.2.1 on 2023-06-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_user_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
