# Generated by Django 4.2.1 on 2023-06-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_remove_user_balance_remove_user_expenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
