# Generated by Django 4.2.1 on 2023-06-22 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_user_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
    ]
